### ISSUE TITLE
[feat] 검색 피드에서 카테고리 필터 구현

### ISSUE THREAD

**Issue by JinuCheon** [Nexters/phochak-server#166]
## 📝 구현 목록

카테고리(여행/맛집/카페) 필터 구현 - 해시태그 검색과 함께 쓸 수 있도록 구현해야 함.

논의 결과, 정렬은 사용성이 떨어질 것 같아서 사용하지 않기로 결정했습니다.
대신 이번달 안으로 인기 게시글 알고리즘 만드는 것으로..

- [ ] 검색창 API에서 카테고리 필터 구현
- [ ] API 사용성을 위해, 검색 카테고리를 빈 값을 넣어도 동작할 수 있도록 구현

<br>

## 💡 참고자료

- (없다면 이 항목을 지워주세요.)

**Comment by seyoung755** [comment]
작업하느라 고생중이군요 ㅠㅠ ... 시간날때 도울수있도록 하겠습니다..!
